<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

namespace Ping;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ping.HelloReqest</code>
 */
class HelloReqest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string toMessage = 1;</code>
     */
    private $toMessage = '';

    public function __construct() {
        \GPBMetadata\Ping::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string toMessage = 1;</code>
     * @return string
     */
    public function getToMessage()
    {
        return $this->toMessage;
    }

    /**
     * Generated from protobuf field <code>string toMessage = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->toMessage = $var;

        return $this;
    }

}

