<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

namespace GPBMetadata;

class Ping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a0a70696e672e70726f746f120470696e6722200a0b48656c6c6f" .
            "52657165737412110a09746f4d65737361676518012001280922230a0d48" .
            "656c6c6f526573706f6e736512120a0a7265734d65737361676518012001" .
            "280932390a0450696e6712310a0548656c6c6f12112e70696e672e48656c" .
            "6c6f5265716573741a132e70696e672e48656c6c6f526573706f6e736522" .
            "00620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

